apiVersion: v1
kind: Service
metadata:
  name: {{ include "registry-helm.fullname" . }}-gistry
  labels:
  {{- include "registry-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.gistry.type }}
  selector:
    app: registry
  {{- include "registry-helm.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.gistry.ports | toYaml | nindent 2 -}}