apiVersion: v1
kind: Pod
metadata:
  name: {{ include "registry-helm.fullname" . }}-gistry-pod
  labels:
    app: registry
  {{- include "registry-helm.labels" . | nindent 4 }}
spec:
  containers:
  - env:
    - name: REGISTRY_AUTH
      value: htpasswd
    - name: REGISTRY_AUTH_HTPASSWD_REALM
      value: Registry Realm
    - name: REGISTRY_AUTH_HTPASSWD_PATH
      value: /auth/htpasswd
    - name: REGISTRY_HTTP_TLS_CERTIFICATE
      value: /certs/tls.crt
    - name: REGISTRY_HTTP_TLS_KEY
      value: /certs/tls.key
    image: registry:2.6.2
    name: registry
    volumeMounts:
    - mountPath: /var/lib/registry
      name: repo-vol
    - mountPath: /certs
      name: certs-vol
      readOnly: true
    - mountPath: /auth
      name: auth-vol
      readOnly: true
  volumes:
  - name: repo-vol
    persistentVolumeClaim:
      claimName: docker-repo-pvc
  - name: certs-vol
    secret:
      secretName: certs-secret
  - name: auth-vol
    secret:
      secretName: auth-secret