apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "registry-helm.fullname" . }}-po-pv
  labels:
  {{- include "registry-helm.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /tmp/repository